### ISSUE TITLE
Could not open NodeRequirer.sublime-settings || No JSON object could be decoded

### ISSUE THREAD

**Issue by ssaunders** [ganemone/NodeRequirer#79]
OS: Mac 10.9.5
Sublime 3 (Build 3083)
*Let me know what other data you want.*

I first saw this error when attempting to use the require command:
```
Unable to open /Users/stephens/Library/Application Support/Sublime Text 3/Packages/User/NodeRequirer.sublime-settings
Using node.js path on 'osx': /usr/local/bin/node
Using jscs path on 'osx': /usr/local/bin/jscs
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 63, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 271, in run
    file_name=view.file_name()
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/RequireSnippet.py", line 30, in __init__
    self.jscs_options = get_jscs_options(self.file_name)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 180, in get_jscs_options
    open(jscsrc_path, 'r', encoding='UTF-8'))
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 171, in lazy_parse_comment_json
    return json.loads(json_text)
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```

I then created a file at the appropriate path with "{}" as the text, and got this error:
```
Unable to open /Users/stephens/Library/Application Support/Sublime Text 3/Packages/User/NodeRequirer.sublime-settings
SublimeLinter: json activated: <builtin> 
reloading Packages/User/NodeRequirer.sublime-settings
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 63, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 271, in run
    file_name=view.file_name()
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/RequireSnippet.py", line 30, in __init__
    self.jscs_options = get_jscs_options(self.file_name)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 180, in get_jscs_options
    open(jscsrc_path, 'r', encoding='UTF-8'))
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 171, in lazy_parse_comment_json
    return json.loads(json_text)
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```

I then added a the example setting object from the Readme, and am now getting this error:
```
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 63, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 271, in run
    file_name=view.file_name()
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/RequireSnippet.py", line 30, in __init__
    self.jscs_options = get_jscs_options(self.file_name)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 180, in get_jscs_options
    open(jscsrc_path, 'r', encoding='UTF-8'))
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 171, in lazy_parse_comment_json
    return json.loads(json_text)
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```

**Comment by ganemone** [comment]
Sorry it has taken me so long to get back to you. Are you still having this issue with version 1.0.0?

**Comment by ssaunders** [comment]
You're fine. Yes, I am still seeing this issue.

**Comment by ganemone** [comment]
Can you post your sublime-settings file?

**Comment by ssaunders** [comment]
```
{
    // Requiring an item that matches a key in the dictionary
    // will transform the rendered require to the value.
    // E.g. var _ = require('lodash') if {'lodash': '_'}
    "alias": {
        "backbone": "Backbone",
        "backbone.marionette": "Marionette",
        "bluebird": "Promise",
        "cheerio": "$",
        "ember": "Ember",
        "handlebars": "Handlebars",
        "highland": "hl",
        "hogan.js": "Hogan",
        "leaflet": "L",
        "lodash": "_",
        "string": "S",
        "jquery": "$",
        "jquery-ui": "ui",
        "knockout": "ko",
        "mustache": "Mustache",
        "node-tap": "test",
        "pouchdb": "PouchDB",
        "prova": "test",
        "es6-promise": "Promise",
        "native-promise-only": "Promise",
        "ractive": "Ractive",
        "immutable": "Immutable",
        "ramda": "R",
        "react": "React",
        "react-dom": "ReactDOM",
        "react-addons-clone-with-props": "cloneWithProps",
        "react-addons-create-fragment": "createFragment",
        "react-addons-css-transition-group": "CSSTransitionGroup",
        "react-addons-linked-state-mixin": "LinkedStateMixin",
        "react-addons-pure-render-mixin": "PureRenderMixin",
        "react-addons-shallow-compare": "shallowCompare",
        "react-addons-transition-group": "TransitionGroup",
        "react-addons-update": "update",
        "roslib": "ROS",
        "rsvp": "RSVP",
        "underscore": "_",
        "socket.io": "io",
        "spine": "Spine",
        "tap": "test",
        "three": "THREE",
        "q": "Q",
        "qunit": "QUnit",
        "zepto": "$",
        "graceful-fs": "fs",
        "findup-sync": "findup",
        "mime-types": "mime",
        "gulp-util": "gutil",
        "iconv-lite": "iconv",
        "event-stream": "es",
        "stream-line-wrapper": "LineWrapper",
        "stream-to-array": "streamToArray",
        "raw-body": "getRawBody",
        "aws-sdk": "AWS",
        "connect-dynamodb": "DynamoDBStore",
        "connect-mysql": "MySQLStore",
        "connect-sdb": "SdbStore",
        "connect-sqlite3": "SQLiteStore",
        "package.json": "pkg",
        "tape": "test",
        "sequelize": "Sequelize",
        "r": "rethinkdb",
        "r": "rethinkdbdash"
    },

    // Common "alias" patterns that can be expressed using regular expressions
    "alias-pattern": {
        "gulp-(.+)": "\\1",
        "lodash\\.(.+)": "\\1"
    },

    // Use 'single' or "double" quotes
    "quotes": "single",

    // Don't insert semicolons at the end of lines
    "semicolon_free": false,

    // Use 'var', 'const', or 'let' variable declarations
    "var": "var",

    // File extensions to omit when doing a local require.
    // E.g. require('./filename') for ./filename.js if js is omited
    "omit_extensions": ["js"],

    // Use Bluebird style promisification of libraries
    // This setting is best set per-project
    "usePromisify": false,

    // Settings that allow you to override what promisify wrapper is used
    "promise": {
        "promisify": "Promise.promisify",
        "promisifyAll": "Promise.promisifyAll"

    },

    // A list of packages that should be promisified with Promise.promisify
    "promisify": [
        "which",
        "rimraf"
    ],

    // A list of packages that should be promisified with Promise.promisifyAll
    "promisifyAll": [
        "fs",
        "graceful-fs",
        "dns",
        "zlib",
        "redis",
        "mongodb",
        "mongoose",
        "mkdirp",
        "winston",
        "xml2js",
        "jsdom",
        "fs-extra",
        "prompt",
        "nodemailer",
        "ncp",
        "pg"
    ],

    // Use ES6 Import Style
    // i.e. import module from module
    "import": false,

    // Allow for tab completion through require statement
    "snippets": true,

    // find and import undefined vars with ESLint
    // when "Require From Word" called without selected word
    "import_undefined_vars": false
}
```

**Comment by ganemone** [comment]
Removing the comments should fix this.

**Comment by ssaunders** [comment]
Removed all comments, file now looks like below, and still seeing issue:
```
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 63, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 263, in run
    file_name=view.file_name()
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/RequireSnippet.py", line 32, in __init__
    self.jscs_options = get_jscs_options(self.file_name)
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 180, in get_jscs_options
    open(jscsrc_path, 'r', encoding='UTF-8'))
  File "/Users/stephens/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/src/utils.py", line 171, in lazy_parse_comment_json
    return json.loads(json_text)
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```


```{
    "alias": {
        "backbone": "Backbone",
        "backbone.marionette": "Marionette",
        "bluebird": "Promise",
        "cheerio": "$",
        "ember": "Ember",
        "handlebars": "Handlebars",
        "highland": "hl",
        "hogan.js": "Hogan",
        "leaflet": "L",
        "lodash": "_",
        "string": "S",
        "jquery": "$",
        "jquery-ui": "ui",
        "knockout": "ko",
        "mustache": "Mustache",
        "node-tap": "test",
        "pouchdb": "PouchDB",
        "prova": "test",
        "es6-promise": "Promise",
        "native-promise-only": "Promise",
        "ractive": "Ractive",
        "immutable": "Immutable",
        "ramda": "R",
        "react": "React",
        "react-dom": "ReactDOM",
        "react-addons-clone-with-props": "cloneWithProps",
        "react-addons-create-fragment": "createFragment",
        "react-addons-css-transition-group": "CSSTransitionGroup",
        "react-addons-linked-state-mixin": "LinkedStateMixin",
        "react-addons-pure-render-mixin": "PureRenderMixin",
        "react-addons-shallow-compare": "shallowCompare",
        "react-addons-transition-group": "TransitionGroup",
        "react-addons-update": "update",
        "roslib": "ROS",
        "rsvp": "RSVP",
        "underscore": "_",
        "socket.io": "io",
        "spine": "Spine",
        "tap": "test",
        "three": "THREE",
        "q": "Q",
        "qunit": "QUnit",
        "zepto": "$",
        "graceful-fs": "fs",
        "findup-sync": "findup",
        "mime-types": "mime",
        "gulp-util": "gutil",
        "iconv-lite": "iconv",
        "event-stream": "es",
        "stream-line-wrapper": "LineWrapper",
        "stream-to-array": "streamToArray",
        "raw-body": "getRawBody",
        "aws-sdk": "AWS",
        "connect-dynamodb": "DynamoDBStore",
        "connect-mysql": "MySQLStore",
        "connect-sdb": "SdbStore",
        "connect-sqlite3": "SQLiteStore",
        "package.json": "pkg",
        "tape": "test",
        "sequelize": "Sequelize",
        "r": "rethinkdb",
        "r": "rethinkdbdash"
    },

    "alias-pattern": {
        "gulp-(.+)": "\\1",
        "lodash\\.(.+)": "\\1"
    },

    "quotes": "single",

    "semicolon_free": false,

    "var": "var",

    "omit_extensions": ["js"],

    "usePromisify": false,

    "promise": {
        "promisify": "Promise.promisify",
        "promisifyAll": "Promise.promisifyAll"

    },

    "promisify": [
        "which",
        "rimraf"
    ],

    "promisifyAll": [
        "fs",
        "graceful-fs",
        "dns",
        "zlib",
        "redis",
        "mongodb",
        "mongoose",
        "mkdirp",
        "winston",
        "xml2js",
        "jsdom",
        "fs-extra",
        "prompt",
        "nodemailer",
        "ncp",
        "pg"
    ],

    "import": false,

    "snippets": true,

    "import_undefined_vars": false
}
```

I don't develop for Sublime. Could I edit the code in that file to see what's going on?

**Comment by ganemone** [comment]
Oh - actually looks like that isn't the issue. Looks like NodeRequirer is trying to parse a .jscsrc config file and is failing. I can fix this latter today, busy atm however.

**Comment by ssaunders** [comment]
Probably because it had comments in it. I removed them and it worked. So the fault was mine, but an error message would make it more discoverable.

**Comment by megawac** [comment]
@ganemone we should probably just drop `jscs` support as jscs has officially been deprecated in favour of jshint

**Comment by megawac** [comment]
Also dupe of #52
